version: '3.3'
services:
  social-network-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'socialnetwork'
      MYSQL_USER: 'nodeuser'
      MYSQL_PASSWORD: 'nodeuser'
      MYSQL_ROOT_PASSWORD: 'nodeuser'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: